import { RequestHandler } from 'express';

// Wraps a RequetHandler function in a Promise.resolve()
// Any error generated by the function are handled by the catch function,
//   calling the next function while passing the error
const asyncHandler =
    (func: RequestHandler): RequestHandler =>
    (req, res, next) =>
        Promise.resolve(func(req, res, next)).catch(next);

export default asyncHandler;
